export const PERSONAS = [
  "the poet",
  "the warlock",
  "the fool",
  "the devil",
  "the witch",
  "the oracle",
  "the child",
  "the beast",
  "the lonely man",
  "the existential self",
  "the artist",
  "the writer",
  "the observer",
  "the lost soul",
  "the wizard",
  "the boy king",
  "the soul searcher",
  "the philosopher",
  "the spider",
  "the sad cat",
  "the mystic",
  "the fortune teller",
  "the crone",
  "the nymph",
  "the chieftain",
  "the lover",
  "the fighter",
  "the animal",
  "the mole",
  "the monkey",
  "the dirty dog",
  "the walrus",
  "the hamster",
  "the rock lobster",
  "the almighty",
  "the wandering star",
  "the prophet",
  "the omen",
  "the quiet storm",
  "the broken compass",
  "the dreamer",
  "the muse",
  "the pilgrim",
  "the conductor",
  "the specter",
  "the handsome prince",
  "the transient",
  "the stranger",
  "the butterfly",
  "the moon",
  "the sun",
  "the shadow",
  "the dawn",
  "the saint",
  "the wolf",
  "the conjurer",
  "the minor arcana",
  "the flame",
  "the optimist",
  "the cynic",
  "the spirit",
  "the hero",
  "the bone collector",
  "the astral visitor",
  "the wise one",
  "the ghost",
  "the ritualist",
  "the serpent",
  "the vessel",
  "the meditator",
  "the runner",
  "the snake",
  "the rat",
  "the tiger",
  "the ox",
]

export const getRandomPersonas = (count: number = 3): string[] => {
  const shuffled = [...PERSONAS].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
